micronaut:
  application:
    name: architect-engine
  server:
    port: 9292

  engine:
    project:
      cache:
        enabled: false
    plugin:
      cache:
        enabled: false

architect:
  cloud:
    enabled: false
    url: http://localhost:8080
    engine-id: ${ARCHITECT_ENGINE_ID:}